import { NextResponse } from 'next/server';
const natural = require('natural');

// ═══════════════════════════════════════════════════════════════════════════════
//  ULTRA-COMPREHENSIVE NAÏVE-BAYES TEXT CLASSIFIER
//  Categories: action item | decision | question | reference
//  Total training phrases: ~1 400+
// ═══════════════════════════════════════════════════════════════════════════════

export async function POST(req: Request) {
  try {
    const { text } = await req.json();

    const classifier = new natural.BayesClassifier();

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  1. ACTION ITEMS  ░░
    // ─────────────────────────────────────────────────────────────────────────
    const actionPhrases: string[] = [

      // ── Frontend / UI ──────────────────────────────────────────────────────
      'build the login page',
      'build the registration form',
      'build the dashboard layout',
      'build the navigation menu',
      'build the sidebar component',
      'build the header and footer',
      'build the checkout flow',
      'build the user profile page',
      'build the landing page from the mockup',
      'build the onboarding wizard',
      'build the file upload widget',
      'build the notification banner component',
      'build the search results page',
      'build the multi step form',
      'build the chat interface',
      'build the calendar component',
      'build the data table with sorting and filtering',
      'create a rest api endpoint',
      'create the user profile page',
      'create the settings panel',
      'create a reusable button component',
      'create the onboarding flow screens',
      'create the toast notification system',
      'create the modal dialog component',
      'create the breadcrumb navigation',
      'create the dropdown menu component',
      'create the image carousel',
      'create the rich text editor',
      'create the date picker component',
      'create the autocomplete search input',
      'create the stepper component for onboarding',
      'implement oauth authentication',
      'implement dark mode toggle',
      'implement infinite scroll on the feed',
      'implement real time notifications',
      'implement drag and drop file upload',
      'implement responsive design for mobile',
      'implement keyboard navigation accessibility',
      'implement lazy loading for images',
      'implement skeleton loaders for the feed',
      'implement multi language support',
      'implement two factor authentication flow',
      'implement the forgot password flow',
      'implement the email verification step',
      'implement session expiry warnings',
      'implement the side panel animation',
      'develop the payment module',
      'develop the admin dashboard',
      'develop the reporting module',
      'develop the analytics charts',
      'develop the push notification service',
      'develop the user activity timeline',
      'develop the subscription billing page',
      'develop the role based access control ui',
      'code the search functionality',
      'code the filter and sort options',
      'code the pagination component',
      'code the currency formatter utility',
      'code the form field validation library',
      'add the dark mode feature',
      'add tooltips to all form fields',
      'add loading skeleton screens',
      'add form validation for all inputs',
      'add unit tests for the login component',
      'add error boundaries around route pages',
      'add cypress end to end tests for checkout',
      'add storybook stories for the design system',
      'add accessibility aria labels to all icons',
      'add the cookie consent banner',
      'add the help tooltip overlay',
      'add the feedback rating widget',
      'design the user interface mockup',
      'design the mobile app wireframes',
      'create the wireframe prototype',
      'design the color palette and typography tokens',
      'design the empty state illustrations',
      'design the error page layouts',
      'design the responsive grid system',

      // ── Backend / API ──────────────────────────────────────────────────────
      'fix the null pointer exception',
      'fix the broken api endpoint',
      'fix the cors error on the server',
      'fix the session timeout bug',
      'fix the data validation issue',
      'fix the race condition in payment flow',
      'fix the authentication middleware bug',
      'fix the broken pagination in the api',
      'fix the incorrect http status codes',
      'fix the serialization error in the response',
      'fix the database transaction rollback issue',
      'fix the memory leak in the event listener',
      'fix the off by one error in the loop',
      'fix the stale closure bug in react hook',
      'fix the incorrect regex in email validation',
      'debug the production crash',
      'debug the memory leak in the worker',
      'debug the failing webhook handler',
      'debug the slow graphql resolver',
      'debug the intermittent 503 error',
      'debug the flaky unit test',
      'debug the deadlock in the database',
      'debug the circular dependency in modules',
      'debug the nan issue in calculations',
      'deploy the latest build to staging',
      'deploy the hotfix to production',
      'deploy the microservice to kubernetes',
      'deploy the canary release to 10 percent traffic',
      'deploy the frontend to cloudfront',
      'deploy the backend to elastic beanstalk',
      'deploy the serverless functions to aws lambda',
      'deploy the scheduled jobs to ecs',
      'setup the docker environment',
      'setup the ci cd pipeline',
      'setup the monitoring alerts',
      'setup ssl certificates for the domain',
      'setup the staging environment',
      'setup the local development environment',
      'setup the database seed scripts',
      'setup the feature flag system',
      'setup the log aggregation pipeline',
      'setup the api rate limiting middleware',
      'setup the health check endpoints',
      'setup the chaos engineering tests',
      'configure nginx reverse proxy',
      'configure the environment variables',
      'configure the database connection pool',
      'configure rate limiting on the api',
      'configure the cors whitelist',
      'configure the load balancer health checks',
      'configure the auto scaling rules',
      'configure the cloudwatch dashboards',
      'configure the s3 bucket policies',
      'configure the vpc security groups',
      'install the dependency packages',
      'install the security patches',
      'install the monitoring agent on all servers',
      'install the ssl certificate on the load balancer',
      'integrate stripe payment gateway',
      'integrate sendgrid for email service',
      'integrate google analytics',
      'integrate the third party crm',
      'integrate the sms notification service',
      'integrate plaid for bank account linking',
      'integrate twilio for voice calls',
      'integrate algolia for full text search',
      'integrate intercom for customer support chat',
      'integrate segment for event tracking',
      'integrate launchdarkly for feature flags',
      'integrate datadog for application monitoring',
      'integrate pagerduty for on call alerts',
      'update the npm packages to latest',
      'update the api documentation',
      'update the user permissions logic',
      'update the password hashing algorithm',
      'update the terms of service page',
      'update the privacy policy document',
      'update the error message strings',
      'update the email templates',
      'update the database seed data',
      'upgrade node to version 20',
      'upgrade the database to postgres 16',
      'upgrade the ssl certificate',
      'upgrade react to version 18',
      'upgrade the webpack config to version 5',
      'upgrade the kubernetes cluster version',
      'refactor the user service class',
      'refactor the authentication middleware',
      'refactor the database models',
      'refactor the api response format',
      'refactor the global state management',
      'refactor the legacy helper functions',
      'refactor the monolithic service into modules',
      'refactor the test suite to use factories',
      'optimize the slow database query',
      'optimize the image compression pipeline',
      'optimize the docker image size',
      'optimize the webpack bundle',
      'optimize the graphql query batching',
      'optimize the redis cache hit rate',
      'optimize the api payload size',
      'optimize the render performance of the list',
      'improve the api response time',
      'improve the error handling logic',
      'improve the test coverage percentage',
      'improve the typescript type definitions',
      'improve the code documentation comments',
      'enhance the logging system',
      'enhance the caching strategy',
      'enhance the retry logic with exponential backoff',
      'enhance the audit trail logging',
      'clean up the unused imports',
      'clean up the dead code',
      'clean up the deprecated api calls',
      'clean up the old feature flags',
      'clean up the stale git branches',
      'clean up the orphaned database records',
      'rewrite the legacy authentication module',
      'rewrite the data export function',
      'rebuild the frontend from scratch',
      'rebuild the notification system',
      'rebuild the report generation engine',

      // ── DevOps / Infrastructure ────────────────────────────────────────────
      'migrate the database to postgresql',
      'migrate the app to aws lambda',
      'migrate the storage to s3',
      'migrate the monolith to microservices',
      'migrate the on premise servers to the cloud',
      'migrate the ci pipeline from jenkins to github actions',
      'migrate user data to the new schema',
      'scale the kubernetes cluster',
      'scale the database read replicas',
      'scale the worker pool for background jobs',
      'monitor the server cpu usage',
      'monitor the api error rate',
      'monitor the database query performance',
      'monitor the queue depth in rabbitmq',
      'monitor the disk usage on all nodes',
      'track the deployment pipeline',
      'track the user engagement metrics',
      'track the conversion funnel in analytics',
      'log all api errors to cloudwatch',
      'log user activity for audit trail',
      'analyze the memory leak',
      'analyze the crash reports',
      'analyze the server performance data',
      'analyze the slow query logs',
      'analyze the bundle size report',
      'investigate the high latency issue',
      'investigate the failed deployments',
      'investigate the security breach attempt',
      'investigate the unusual traffic spike',
      'research the best caching strategy',
      'research microservices architecture patterns',
      'explore graphql as an alternative',
      'explore serverless for cost reduction',
      'automate the regression tests',
      'automate the deployment process',
      'automate the database backups',
      'automate the log rotation',
      'automate the certificate renewal',
      'automate the dependency update process',
      'streamline the release process',
      'secure the api with jwt tokens',
      'secure the admin panel with mfa',
      'protect sensitive user data',
      'protect the api from sql injection',
      'protect against cross site scripting attacks',
      'protect the s3 bucket from public access',
      'harden the server configuration',
      'rotate the api keys and secrets',
      'revoke the compromised access token',
      'patch the open ssl vulnerability',
      'backup the production database',
      'restore the database from backup',
      'sync the local files with remote',
      'sync the staging database with production',
      'merge the feature branch to main',
      'merge the hotfix into the release branch',
      'push the committed changes to remote',
      'commit the code with proper message',

      // ── Documentation ──────────────────────────────────────────────────────
      'write the api documentation',
      'write the system design document',
      'write the runbook for deployment',
      'write the postmortem report',
      'write the test plan for the release',
      'write the technical specification',
      'write the data flow diagram',
      'write the incident response guide',
      'draft the technical specification',
      'draft the product requirements document',
      'draft the security policy',
      'draft the architecture decision record',
      'draft the data retention policy',
      'draft the service level agreement',
      'publish the release notes',
      'publish the changelog',
      'post the engineering blog post',
      'announce the new feature release',
      'announce the scheduled maintenance',
      'document the database schema',
      'document the api endpoints',
      'document the onboarding process',
      'update the readme file',
      'update the contributing guide',
      'update the architecture diagram',
      'maintain the internal wiki',
      'maintain the knowledge base articles',
      'maintain the swagger api spec',
      'create the developer getting started guide',

      // ── Project Management ─────────────────────────────────────────────────
      'schedule the sprint planning meeting',
      'schedule the design review session',
      'schedule the quarterly roadmap review',
      'schedule the one on one with the developer',
      'schedule the all hands meeting',
      'plan the quarterly roadmap',
      'plan the product launch timeline',
      'plan the system migration strategy',
      'plan the disaster recovery drill',
      'organize the backlog tickets',
      'organize the team knowledge base',
      'organize the sprint into epics and stories',
      'prepare the demo for the client',
      'prepare the release checklist',
      'prepare the incident response plan',
      'prepare the monthly status report',
      'prepare the architecture review presentation',
      'send the status report to manager',
      'send the weekly update email',
      'send the deployment notification',
      'send the sprint summary to stakeholders',
      'share the figma designs with team',
      'share the project timeline with stakeholders',
      'review the pull request on github',
      'review the architecture proposal',
      'review the vendor contract',
      'review the security audit findings',
      'review the performance benchmarks',
      'check the failing unit tests',
      'check the code quality metrics',
      'check the server uptime dashboard',
      'check the open pull requests',
      'check the dependency vulnerability report',
      'verify the staging deployment works',
      'verify the data migration results',
      'test the checkout flow end to end',
      'test the mobile app on android devices',
      'test the api with load testing tool',
      'test the email delivery in sandbox',
      'test the rollback procedure',
      'validate the api response schema',
      'validate the business logic rules',
      'validate the user input on the backend',
      'audit the security vulnerabilities',
      'audit the codebase for technical debt',
      'audit the cloud costs and optimize spend',
      'assign the bug to the frontend team',
      'assign the task to the senior developer',
      'delegate the task to the developer',
      'delegate the qa testing to the team',
      'escalate the critical bug to engineering lead',
      'escalate the production incident to on call',
      'prioritize the hotfix above all other tasks',
      'run the database migration script',
      'run the end to end test suite',
      'run the unit tests before pushing',
      'run the security vulnerability scan',
      'execute the load test on staging',
      'generate the weekly analytics report',
      'generate the pdf invoice for the client',
      'generate the summary of sprint results',
      'track the progress of the sprint',
      'monitor the system health dashboard',
      'check the error logs in production',

      // ── Communication ──────────────────────────────────────────────────────
      'call the client about the delay',
      'call the vendor about the invoice',
      'email the stakeholders with update',
      'email the client the final report',
      'message the team on slack',
      'message the designer about revisions',
      'notify the users about maintenance',
      'notify the team about the deployment',
      'inform the manager about the blocker',
      'inform the client about the bug fix',
      'remind the team about the deadline',
      'remind the developer about the code review',
      'follow up on the pending approval',
      'follow up with the client on feedback',
      'ping the devops team about deployment',
      'ping the qa team about test results',
      'reply to the customer support ticket',
      'reply to the design feedback',
      'respond to the code review comments',
      'respond to the stakeholder questions',
      'present the findings to the leadership team',
      'present the new feature demo to the client',

      // ── General / Business ─────────────────────────────────────────────────
      'buy the software license',
      'buy the cloud server subscription',
      'purchase the domain name',
      'purchase the ui component library',
      'order the new laptops for team',
      'arrange the onboarding for new hire',
      'arrange the client meeting next week',
      'manage the vendor contracts',
      'manage the team workload',
      'handle the invoice processing',
      'handle the user data deletion request',
      'complete the performance review',
      'complete the security audit',
      'finish the wireframe designs',
      'finish the accessibility improvements',
      'close the open support tickets',
      'close the stale github issues',
      'submit the expense report',
      'submit the app for app store review',
      'upload the build artifacts',
      'upload the video tutorial to confluence',
      'download the production logs',
      'download the database backup',
      'attach the design files to ticket',
      'attach the error logs to the bug report',
      'forward the email to hr team',
      'forward the bug report to engineering',
      'open a ticket for the login bug',
      'raise an issue in jira',
      'report the bug to the developer',

      // ── Academic / Personal ────────────────────────────────────────────────
      'do the homework assignment',
      'make the school project',
      'make the travel itinerary',
      'edit the assignment notes',
      'edit the blog post before publishing',
      'learn the course syllabus',
      'learn the new programming language',
      'study for the upcoming exam',
      'study the new framework documentation',
      'read the research paper tonight',
      'read the technical book this week',
      'complete the lab report',
      'complete the online certification course',
      'submit the assignment before deadline',
      'submit the job application',
      'prepare the resume for the interview',
      'prepare the presentation for tomorrow',
      'practice the coding challenges daily',
      'register for the tech conference',
      'book the flight tickets for the event',

      // ── NEW: Data / ML / AI ────────────────────────────────────────────────
      'train the machine learning model on the new dataset',
      'fine tune the language model on domain data',
      'clean and preprocess the training dataset',
      'label the images for object detection',
      'annotate the text corpus for ner',
      'evaluate the model accuracy on the test set',
      'deploy the ml model to the inference endpoint',
      'monitor the model drift in production',
      'retrain the recommendation model weekly',
      'build the feature engineering pipeline',
      'write the data ingestion pipeline',
      'schedule the etl job to run nightly',
      'validate the schema of the incoming data',
      'archive the old model versions in s3',
      'analyze the confusion matrix of the classifier',
      'tune the hyperparameters with optuna',
      'run the ab test for the ranking algorithm',
      'calculate the precision recall f1 score',
      'export the trained model to onnx format',
      'document the model card for the ml model',

      // ── NEW: Security & Compliance ─────────────────────────────────────────
      'conduct the penetration test on the api',
      'remediate the critical cve vulnerability',
      'enforce the principle of least privilege',
      'rotate all database passwords in vault',
      'enable encryption at rest for s3 buckets',
      'enable encryption in transit for all services',
      'generate the soc2 compliance report',
      'complete the gdpr data mapping exercise',
      'implement the right to erasure workflow',
      'set up the waf rules to block malicious ips',
      'review the iam roles and remove excess permissions',
      'configure the secrets manager for all credentials',
      'run the dependency audit with npm audit',
      'patch all servers with the latest security update',
      'implement the content security policy headers',

      // ── NEW: Mobile / App ──────────────────────────────────────────────────
      'publish the ios app to the app store',
      'publish the android app to the play store',
      'fix the crash on ios 17 devices',
      'fix the layout bug on samsung galaxy tablets',
      'implement push notifications for the mobile app',
      'add biometric authentication to the mobile app',
      'test the deep linking in the mobile app',
      'reduce the app size by removing unused assets',
      'optimize battery usage in the background service',
      'write the swift unit tests for the auth module',
      'write the kotlin tests for the data layer',
      'submit the app for apple review',
      'respond to the apple review rejection',
      'implement in app purchase flow',
      'implement the offline mode for the mobile app',

      // ── NEW: Cloud / Cost Optimisation ─────────────────────────────────────
      'right size the ec2 instances based on utilization',
      'delete unused elastic ips and snapshots',
      'move infrequent data to s3 glacier',
      'set up the aws cost anomaly detection alerts',
      'tag all cloud resources for cost allocation',
      'purchase reserved instances for baseline workloads',
      'enable spot instances for batch processing jobs',
      'review and clean up unused cloud resources',
      'set up the billing alarm at the monthly threshold',
      'analyze the cloud cost report and reduce spend',
    ];
    actionPhrases.forEach(p => classifier.addDocument(p, 'action item'));

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  2. DECISIONS  ░░
    // ─────────────────────────────────────────────────────────────────────────
    const decisionPhrases: string[] = [

      // ── Tech stack choices ─────────────────────────────────────────────────
      'we decided to use react for the frontend',
      'we decided to use vue instead of angular',
      'we decided to use next js for ssr',
      'we decided to use flutter for mobile',
      'team agreed to go with postgresql database',
      'team agreed to use mongodb for the project',
      'team agreed on using redis for caching',
      'we finalized typescript as the primary language',
      'we finalized the rest api design',
      'we finalized python for the machine learning pipeline',
      'leadership approved using aws for hosting',
      'leadership approved moving to google cloud',
      'leadership approved the new tech stack',
      'we selected graphql over rest api',
      'we selected kubernetes for orchestration',
      'we selected jenkins for the ci cd pipeline',
      'the team chose tailwind css for styling',
      'the team chose material ui components',
      'the team chose to use redux for state management',
      'we opted for redis as the caching layer',
      'we opted for rabbitmq over kafka',
      'we opted for a microservices architecture',
      'management confirmed the tech stack selection',
      'management confirmed moving to the cloud',
      'we locked the architecture design today',
      'we locked the api contract before development',
      'engineering agreed to adopt microservices',
      'engineering agreed to use test driven development',
      'we resolved to drop the legacy system',
      'we resolved to use trunk based development',
      'the decision to use docker is final',
      'the decision to go serverless is confirmed',
      'team concluded to go with agile methodology',
      'team concluded to adopt scrum framework',
      'we settled on two week sprint cycles',
      'we settled on daily standups for the team',
      'product approved the new feature roadmap',
      'product approved the v2 design system',
      'we finalized the api design contract',
      'we finalized the database schema for launch',
      'the team selected the vendor after evaluation',
      'the team selected the new cloud provider',
      'we chose option a after reviewing all proposals',
      'we chose the monolithic approach for now',
      'after discussion we aligned on the approach',
      'after the review we agreed on the solution',
      'we are going with the monorepo structure',
      'we are going with a single page application',
      'we decided to adopt the new design system',
      'we decided on a blue green deployment strategy',
      'we are going with kafka for the event streaming layer',
      'we agreed to use terraform for infrastructure as code',
      'we decided to standardize on python 3 for all services',
      'the team agreed to switch from rest to grpc internally',
      'we selected datadog over new relic for observability',
      'we chose to use pnpm instead of npm',
      'we finalized the use of vitest for unit testing',
      'we agreed to adopt conventional commits standard',
      'we settled on linear for project management going forward',
      'we decided to go with the event driven architecture',

      // ── Project / business outcomes ────────────────────────────────────────
      'the plan is going forward as discussed',
      'the plan is confirmed and communicated to all',
      'we will move forward with the new design',
      'we will proceed with the original timeline',
      'final call was made to delay the launch',
      'final call was made to ship version one without that feature',
      'we decided not to proceed with that approach',
      'we decided not to add the feature this quarter',
      'it is finalized no more changes to the scope',
      'it is confirmed the project is approved',
      'this is the final version of the design',
      'this is the agreed upon architecture going forward',
      'no further revisions will be accepted',
      'no more feature additions in this sprint',
      'the product manager gave final approval',
      'the cto approved the system redesign',
      'the client confirmed the proposal yesterday',
      'the client approved the budget for phase two',
      'the team reached consensus on the priority',
      'the team reached agreement on the sprint goals',
      'we achieved full alignment on the roadmap',
      'we achieved consensus after the retrospective',
      'the board approved the annual budget',
      'the board approved the expansion plan',
      'leadership confirmed the hiring freeze',
      'leadership confirmed the new team structure',
      'we finalized the release date for version two',
      'we finalized the go live date for the platform',
      'the deadline is locked at end of quarter',
      'the budget is capped and confirmed',
      'the requirements are now frozen',
      'the scope is locked for this release',
      'we agreed to proceed with the phased rollout',
      'we agreed to a soft launch first',
      'we decided to launch in two regions first',
      'we decided to open source the internal tool',
      'the team chose to delay the release by two weeks',
      'the team chose to prioritize the mobile app',
      'we accepted the design proposal from the agency',
      'we accepted the revised timeline from the vendor',
      'the go no go decision was made in favour of go',
      'we agreed to sunset the v1 product at end of year',
      'leadership signed off on the new pricing model',
      'the steering committee approved the roadmap for q3',
      'the partnership with the vendor is confirmed',
      'we decided to hire two additional engineers',
      'the headcount increase was approved by finance',
      'the feature will ship in the next major version',
      'we agreed to reduce the scope and ship sooner',
      'the technical review board approved the design',

      // ── Rejections / cancellations ─────────────────────────────────────────
      'the proposal was rejected by management',
      'the proposal was rejected due to budget constraints',
      'we decided to cancel the mobile app project',
      'we decided to cancel the marketing campaign',
      'the feature was dropped from the roadmap',
      'the feature was removed from the sprint',
      'the old api is deprecated starting next month',
      'the old library is deprecated and removed',
      'we are sunsetting the v1 api in q4',
      'we are sunsetting the legacy dashboard',
      'the project was killed due to budget cuts',
      'the project was terminated after the review',
      'this approach was declined by the architect',
      'this solution was rejected by the committee',
      'we rolled back the deployment after the incident',
      'we rolled back the database migration',
      'the manager rejected the overtime request',
      'the manager rejected the architecture change',
      'the idea was voted down by the committee',
      'the idea was shelved for future consideration',
      'the merge request was rejected after review',
      'the vendor proposal was rejected',
      'the third party integration was dropped',
      'the entire module was scrapped and restarted',
      'the initiative was deprioritised for next quarter',
      'the partnership was called off after due diligence',
      'the sprint goal was changed after the mid sprint review',
      'the experiment was stopped after negative results',
      'the ab test was concluded with no significant difference',

      // ── Completion / done states ───────────────────────────────────────────
      'the project is complete and delivered',
      'the project has been signed off by the client',
      'the task has been marked as done',
      'the task is completed and verified',
      'the work is finished and signed off',
      'the work is done and handed over',
      'the deployment was completed successfully',
      'the deployment to production is finished',
      'the migration is done and verified',
      'the migration completed without errors',
      'closing this issue as resolved',
      'closing the ticket after successful fix',
      'marking the pull request as complete',
      'marking the milestone as achieved',
      'the sprint has been wrapped up',
      'the sprint goals have been met',
      'the feature is shipped to production',
      'the feature is live and available to users',
      'the audit is finished and report submitted',
      'the security review is complete',
      'the contract has been signed by both parties',
      'the agreement has been finalized',
      'onboarding is complete for the new developer',
      'onboarding is done for the new team member',
      'the bug has been resolved and closed',
      'the bug fix has been deployed and verified',
      'we confirmed the fix works in production',
      'we confirmed the rollout was successful',
      'the issue was marked as wont fix',
      'the issue was closed as duplicate',
      'the ticket is closed after verification',
      'the ticket resolved and archived',
      'the solution was accepted by the stakeholder',
      'the solution was approved in the review meeting',
      'the alternative approach was rejected in review',
      'the pr was closed without merging',
      'the declined proposal will not be revisited',
      'all acceptance criteria have been met and signed off',
      'the milestone was delivered ahead of schedule',
      'the load test passed and we are ready for launch',
      'the penetration test completed with no critical findings',
      'all blockers have been resolved and the release is green',

      // ── Policy / agreements ────────────────────────────────────────────────
      'all team members agreed to the new policy',
      'everyone agreed to follow the new git workflow',
      'we finalized the incident response plan',
      'we finalized the on call rotation schedule',
      'the new on call schedule has been confirmed',
      'the new code review policy is now in effect',
      'we locked the final sprint goals',
      'we locked the okrs for the quarter',
      'the quarterly okrs have been approved',
      'the annual goals have been signed off',
      'the budget for q3 has been confirmed',
      'the resource allocation has been decided',
      'the vendor contract has been finalized',
      'the partnership agreement has been signed',
      'we approved the design system guidelines',
      'we approved the coding standards document',
      'the team agreed on the branching strategy',
      'the team agreed on the definition of done',
      'we confirmed the testing requirements',
      'we confirmed the deployment process',
      'the data retention policy has been ratified',
      'the sla has been agreed with the client',
      'the nda has been signed by all parties',
      'the new compensation bands have been approved',
      'the performance review framework is finalized',
      'the engineering principles document is accepted',
      'the new meeting cadence has been agreed by the team',
      'the on call escalation path has been approved',
    ];
    decisionPhrases.forEach(p => classifier.addDocument(p, 'decision'));

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  3. QUESTIONS  ░░
    // ─────────────────────────────────────────────────────────────────────────
    const questionPhrases: string[] = [

      // ── How ───────────────────────────────────────────────────────────────
      'how do we fix the authentication issue',
      'how do we handle the rate limiting',
      'how do we prevent the sql injection',
      'how do we rollback the database migration',
      'how do we scale the application',
      'how should we structure the database schema',
      'how should we handle the error responses',
      'how should we organize the project folders',
      'how should we version the api',
      'how can we reduce the api response time',
      'how can we improve the test coverage',
      'how can we automate this manual process',
      'how can we monitor the system in real time',
      'how to implement the caching layer',
      'how to set up the local dev environment',
      'how to deploy the app to production',
      'how to debug the websocket issue',
      'how to connect to the staging database',
      'how does the retry logic work',
      'how does the authentication flow work',
      'how does the data get synced between services',
      'how do we handle race conditions here',
      'how do we ensure data consistency',
      'how do we pass data between components',
      'how do we measure the success of this feature',
      'how do we handle backward incompatible changes',
      'how do we manage secrets in the local environment',
      'how do we enforce code style in the project',
      'how do we recover from a failed database migration',
      'how can we reduce the docker build time',
      'how should we handle retries for failed webhook deliveries',
      'how do we test the payment flow without real money',
      'how do we get visibility into the queue depth',
      'how do we support multiple tenants in the database',

      // ── Why ───────────────────────────────────────────────────────────────
      'why is the build failing in ci',
      'why is the test suite so slow',
      'why is the api returning 401 errors',
      'why is the docker container crashing',
      'why does the login fail on mobile',
      'why does the page load so slowly',
      'why does the payment fail for some users',
      'why does the app crash on ios 16',
      'why is the server throwing a 500 error',
      'why is the memory usage increasing over time',
      'why is the database connection failing',
      'why is the queue backing up',
      'why did the deployment break production',
      'why did the migration fail halfway',
      'why did the tests pass locally but fail in ci',
      'why did the user data get corrupted',
      'why is the memory usage so high',
      'why is the cpu spiking during the night',
      'why are the logs not appearing in cloudwatch',
      'why are users being logged out randomly',
      'why is the cache miss rate so high',
      'why is the latency higher on the eu region',
      'why did the scheduled job not run last night',
      'why is the s3 upload failing for large files',
      'why are emails not being delivered to gmail users',
      'why does the mobile app not work on older android versions',

      // ── What ──────────────────────────────────────────────────────────────
      'what is the best approach to handle this',
      'what is the right way to structure the api',
      'what is the recommended solution here',
      'what should we do about the recurring bug',
      'what should we prioritize this sprint',
      'what should we use for real time communication',
      'what is causing the high latency',
      'what is causing the app to crash',
      'what is causing the data inconsistency',
      'what is the current status of the feature',
      'what is the progress on the migration',
      'what is the status of the deployment',
      'what is blocking the release',
      'what is preventing the tests from passing',
      'what is the bottleneck in the pipeline',
      'what are the next steps for the project',
      'what are the acceptance criteria for this ticket',
      'what are the performance requirements',
      'what technology should we use for real time updates',
      'what library should we use for state management',
      'what framework is best for this use case',
      'what is the expected behaviour here',
      'what is the expected output of this function',
      'what is the rollback plan if this fails',
      'what do you think about the new design',
      'what do you think about switching to graphql',
      'what is the plan for the database migration',
      'what is the testing strategy for this release',
      'what happens when the token expires',
      'what happens if the payment fails midway',
      'what are the performance benchmarks',
      'what is the difference between these two approaches',
      'what are the security implications of this change',
      'what is the impact of this change on existing users',
      'what does the error message mean exactly',
      'what is the estimated time to complete this task',
      'what tool should we use to monitor this',
      'what is the data model for the new feature',
      'what is the risk of deploying this now',
      'what alternative approaches have we considered',
      'what is the current p95 latency of the api',

      // ── When / Where ──────────────────────────────────────────────────────
      'when is the deadline for the release',
      'when is the next sprint starting',
      'when will the feature be ready for testing',
      'when can we expect the bug fix',
      'when can we start the performance testing',
      'when should we schedule the code review',
      'when are we doing the production deployment',
      'when will the new developer join the team',
      'where is the configuration file stored',
      'where is the environment variable set',
      'where is the bug happening in the code',
      'where is the bottleneck in the pipeline',
      'where should we log the error details',
      'where is the latest build deployed',
      'where do we store the api keys',
      'where is the documentation for this service',
      'when did this regression get introduced',
      'when was the last deployment to production',
      'when is the on call rotation changing',
      'where do we track our okrs',

      // ── Who ───────────────────────────────────────────────────────────────
      'who is responsible for the deployment',
      'who owns this part of the codebase',
      'who will handle the database migration',
      'who is assigned to fix this critical bug',
      'who is the point of contact for this vendor',
      'who approved this change to production',
      'who is reviewing the pull request',
      'who is the on call engineer this week',
      'who wrote this part of the code',
      'who is handling the client communication',
      'who can help me with the infrastructure setup',
      'who made the last change to this file',
      'who is the product owner for this feature',
      'who should i talk to about the budget',

      // ── Can / Could ───────────────────────────────────────────────────────
      'can we ship this feature before friday',
      'can we merge this without more tests',
      'can we revert the last deployment',
      'can we use this library commercially',
      'can you explain the new architecture design',
      'can you clarify the acceptance criteria',
      'can you review my pull request',
      'can someone help debug the issue',
      'can we add this feature to the current sprint',
      'can we postpone the release to next week',
      'can we access the production logs',
      'can we run the migration on a weekend',
      'could we improve the current implementation',
      'could we automate this workflow',
      'could this cause a performance issue in prod',
      'can we test this without affecting live users',
      'can we get a rollback ready before deploying',
      'can we increase the rate limit temporarily',

      // ── Should / Shall ────────────────────────────────────────────────────
      'should we refactor or rewrite the module',
      'should we deploy now or wait for review',
      'should we use rest or graphql for this',
      'should we scale horizontally or vertically',
      'should we add more caching here',
      'should we write more integration tests',
      'should we notify users about this change',
      'should we open source this component',
      'should we consider a different database engine',
      'should we block this issue before release',
      'should we use feature flags for this',
      'should we prioritize this over the current sprint work',
      'should we bring in external help for this',
      'should we page the on call for this issue',

      // ── Is / Are / Do / Did / Have ────────────────────────────────────────
      'is this the correct implementation approach',
      'is the api working as expected in staging',
      'is the fix ready to merge to main',
      'is this behaviour expected from the library',
      'is the data migration tested and verified',
      'is there a workaround for this issue',
      'is there documentation for this api',
      'is this approach scalable for large datasets',
      'is the server load balanced across regions',
      'is there a staging environment to test on',
      'is this breaking change backwards compatible',
      'is the feature behind a flag in production',
      'are we on track for the sprint goals',
      'are we ready to go live this week',
      'are we handling edge cases properly',
      'are there any blockers for the release',
      'are the environment variables set correctly',
      'are we covering this case in the tests',
      'are we compliant with gdpr requirements',
      'are we monitoring this service properly',
      'do we have enough test coverage',
      'do we need to update the documentation',
      'do we have a rollback plan for this',
      'do we need database downtime for this migration',
      'do we support this browser version',
      'did the deployment go through successfully',
      'did the tests pass in the pipeline',
      'did we break anything in the last release',
      'did the migration run without errors',
      'have we considered the security implications',
      'have we informed the stakeholders about the delay',
      'have we tested this on all supported platforms',
      'have we addressed all the review comments',
      'does this comply with gdpr requirements',
      'does this break any existing functionality',
      'does the fix handle all edge cases',
      'is the service currently down',
      'is there an ongoing incident affecting users',
      'are the alerts firing for the right reasons',
      'did we get customer sign off on this',
      'is this change covered by the existing tests',

      // ── Open / conversational ─────────────────────────────────────────────
      'any thoughts on the new api design',
      'any suggestions for improving the performance',
      'any ideas on how to reduce the build time',
      'any update on the client feedback',
      'any update on the progress of this task',
      'any blockers i should know about',
      'any concerns about this approach',
      'what do you think about switching frameworks',
      'how about using a message queue instead',
      'what if we use serverless functions here',
      'what if we cache the api responses',
      'what if we split this into two services',
      'need clarification on the feature requirements',
      'need more context about this ticket',
      'please explain the expected output format',
      'help me understand the deployment process',
      'can you walk me through the code logic',
      'what is the root cause of this crash',
      'what is the status of the pull request',
      'how do we test this in isolation',
      'which library is better for this use case',
      'which approach has lower latency',
      'can we demo this to the client tomorrow',
      'is there a faster way to do this',
      'is there an existing solution for this',
      'status update please',
      'any progress on the bug fix',
      'thoughts on this implementation',
      'feedback on the design please',
      'opinions on the new feature approach',
      'can someone double check my logic here',
      'is my understanding correct',
      'does anyone have experience with this library',
      'what is everyone availability for the meeting',
      'does this look right to you',
      'am i missing something here',
      'any volunteers to lead the investigation',
      'what is the expected sla for this endpoint',
      'how long will the migration take',
      'is this a p1 or p2 incident',
    ];
    questionPhrases.forEach(p => classifier.addDocument(p, 'question'));

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  4. REFERENCES  ░░
    // ─────────────────────────────────────────────────────────────────────────
    const referencePhrases: string[] = [

      // ── URLs ──────────────────────────────────────────────────────────────
      'https://github.com/org/repo/pull/42',
      'https://github.com/org/repo/issues/123',
      'https://github.com/org/repo/commit/abc1234',
      'https://www.figma.com/file/abc123/dashboard-design',
      'https://www.figma.com/proto/xyz/mobile-flow',
      'https://docs.google.com/document/d/xyz/edit',
      'https://docs.google.com/spreadsheets/d/abc/edit',
      'https://docs.google.com/presentation/d/xyz/edit',
      'https://jira.company.com/browse/PROJ-456',
      'https://jira.company.com/browse/BUG-789',
      'https://notion.so/team/meeting-notes',
      'https://notion.so/workspace/roadmap',
      'https://trello.com/b/board123/sprint',
      'https://trello.com/c/card456/feature',
      'https://confluence.atlassian.com/wiki/spaces',
      'https://confluence.company.com/display/ENG/docs',
      'https://stackoverflow.com/questions/12345',
      'https://stackoverflow.com/a/67890',
      'https://developer.mozilla.org/en-us/docs/web/api',
      'https://docs.aws.amazon.com/lambda/latest/dg',
      'https://kubernetes.io/docs/concepts/overview',
      'https://reactjs.org/docs/getting-started.html',
      'http://localhost:3000/api/users',
      'http://localhost:8080/admin/dashboard',
      'https://sentry.io/organizations/team/issues',
      'https://app.datadoghq.com/dashboard/abc',
      'https://grafana.company.com/d/xyz',
      'https://postman.com/collections/abc123',
      'https://swagger.io/tools/swagger-ui/',
      'https://npmjs.com/package/some-library',
      'https://pypi.org/project/some-package',
      'https://hub.docker.com/r/org/image',
      'https://registry.terraform.io/providers/hashicorp',
      'https://linear.app/team/issue/ENG-456',
      'https://app.asana.com/0/project/task/123',
      'https://loom.com/share/video123',
      'https://miro.com/board/abc123',
      'https://lucidchart.com/documents/view/xyz',
      'https://www.draw.io/#Horg/repo/main/arch.xml',
      'https://app.pagerduty.com/incidents/P123456',
      'https://newrelic.com/accounts/123/distributed-tracing',
      'https://circleci.com/gh/org/repo/123',
      'https://app.circleci.com/pipelines/github/org/repo',
      'https://console.aws.amazon.com/cloudwatch/home',
      'https://console.aws.amazon.com/ec2/v2/home',
      'https://portal.azure.com/#blade/resourcegroups',
      'https://console.cloud.google.com/run',
      'https://vercel.com/team/project/deployments',
      'https://app.netlify.com/sites/project/deploys',
      'https://railway.app/project/abc123',
      'https://render.com/services/web/123',
      'https://codeium.com/profile',
      'https://codesandbox.io/s/abc123',
      'https://codepen.io/user/pen/abc123',
      'https://repl.it/@user/project',
      'https://docs.stripe.com/api/charges',
      'https://sendgrid.com/docs/api-reference',
      'https://www.twilio.com/docs/sms/api',
      'https://docs.algolia.com/api-reference',
      'https://segment.com/docs/connections/sources',

      // ── Ticket / issue IDs ─────────────────────────────────────────────────
      'see jira ticket ENG-1234 for the full context',
      'refer to ticket PROJ-789 for background',
      'check the github issue number 567',
      'see the linear issue for more details',
      'refer to the original bug report ENG-456',
      'link to the parent epic EPIC-12',
      'see the related ticket from last sprint',
      'check the sentry issue fingerprint abc123',
      'see the asana task for the full description',
      'jira ticket BE-4521 has the context',
      'trello card id 7abc contains the requirements',
      'see github issue 890 for reproduction steps',
      'linear ENG-203 tracks this feature',
      'asana task 098765 is the parent story',

      // ── PR / code references ───────────────────────────────────────────────
      'see the pull request number 235',
      'refer to pr 456 for the implementation',
      'check the merged pr from last week',
      'see the code in auth.service.ts line 142',
      'refer to function handleAuth in the repo',
      'check the config in the environment file',
      'look at the docker compose file',
      'see the migration file from january',
      'refer to commit abc1234 for the original change',
      'check the git blame on line 88',
      'see the branch feature slash payment for context',
      'look at the stash entry for the wip changes',
      'refer to the tag v2.1.0 in the repository',
      'see the release branch for the hotfix',
      'check the changelog entry for version 3',
      'pull request 512 contains the full implementation',
      'see commit 8f3a2c1 where this was introduced',
      'check branch hotfix slash login for the patch',
      'diff on line 67 of userController.ts',
      'see the code comment in utils/formatter.js',

      // ── Tool / dashboard references ────────────────────────────────────────
      'check the error in sentry dashboard',
      'look at the datadog logs from last night',
      'see the grafana dashboard for metrics',
      'refer to the cloudwatch alarm',
      'check the kibana log stream',
      'see the new relic trace for the slow query',
      'look at the pagerduty incident timeline',
      'refer to the postman collection for api tests',
      'see the swagger docs for the endpoint spec',
      'check the jenkins build log',
      'look at the github actions run',
      'see the circleci pipeline for the failure',
      'check the vercel deployment preview link',
      'see the amplitude dashboard for user funnel',
      'refer to the mixpanel report for retention data',
      'check the hotjar recording for the ux issue',
      'see the lighthouse report for performance scores',
      'look at the sonarqube code quality report',
      'check the codecov coverage report',
      'see the snyk vulnerability report',

      // ── Document / file references ─────────────────────────────────────────
      'see the attached architecture diagram',
      'refer to the design file in figma',
      'check the confluence page for details',
      'link to the api documentation here',
      'look at the spreadsheet in google drive',
      'check the readme for setup instructions',
      'see the onboarding doc for new engineers',
      'refer to the adr document for the decision log',
      'refer to the system design document',
      'look at the postmortem from last month',
      'see the runbook for the deployment process',
      'check the playbook for the incident response',
      'see the slide deck from the design review',
      'refer to the meeting notes from tuesday',
      'see the slack thread from yesterday',
      'refer to the email from the client last week',
      'check the notion page for the roadmap',
      'see the miro board for the brainstorm session',
      'look at the recording of the planning meeting',
      'refer to the loom video walkthrough',
      'check the google doc for the product spec',
      'see the excel sheet for the test matrix',
      'refer to the pdf report for the audit findings',
      'look at the draw io diagram for the system overview',
      'see the technical design doc in confluence',
      'check the shared one drive folder for assets',
      'refer to the airtable base for the content plan',
      'see the zeplin annotation for the spacing values',
      'check the invision prototype for the user flow',

      // ── Person / meeting references ────────────────────────────────────────
      'cc john on this email',
      'mentioned in the meeting with sarah',
      'as discussed with the product team',
      'per the conversation with the client',
      'reference from the cto presentation',
      'as noted by the architect in the review',
      'as per the discussion in standup',
      'as mentioned by the pm in the sync',
      'based on the feedback from the designer',
      'according to what was said in the last retrospective',
      'per alice comment in the pull request',
      'following up on the conversation with bob yesterday',
      'as raised by the qa lead in the bug triage',
      'in reference to the all hands from last friday',
      'as per the vendor meeting on monday',

      // ── Version / release references ───────────────────────────────────────
      'version 2.4.1 released last tuesday',
      'version 3.0.0 is the stable release',
      'see changelog for v3.0.0',
      'refer to release notes from november',
      'check the hotfix branch from last week',
      'see commit abc1234 for the original change',
      'refer to tag v1.2.0 in the repository',
      'check the npm version 4.5.2 release',
      'see the docker image tag 1.0.3 stable',
      'release v4.1.0 introduced this behaviour',
      'version 5.0.0 breaking change documented in migration guide',
      'see the github release page for v2.3.0',
      'check the npm changelog for version 6.0.1',
      'docker tag latest was updated yesterday',

      // ── Miscellaneous references ───────────────────────────────────────────
      'figma link for the new onboarding flow',
      'github issue 567 has the full context',
      'the meeting recording is in google drive',
      'slide deck from the all hands is attached',
      'the diagram in notion covers this topic',
      'the architecture decision record is here',
      'the technical design doc is in confluence',
      'the spreadsheet tracks the current assignments',
      'the shared calendar has the sprint schedule',
      'the knowledge base article covers this case',
      'pr description has the full change summary',
      'the dashboard link is pinned in the slack channel',
      'the design tokens are documented in storybook',
      'the api contract is defined in the openapi yaml',
      'the erd is in the database folder of the repo',
      'refer to the rfc document in the proposals folder',
      'the cost analysis spreadsheet is shared in teams',
      'the recorded demo is in the drive shared folder',
      'see the postman environment file in the repo root',
      'refer to the schema registry for the event definitions',
    ];
    referencePhrases.forEach(p => classifier.addDocument(p, 'reference'));

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  TRAIN  ░░
    // ─────────────────────────────────────────────────────────────────────────
    classifier.train();

    // ─────────────────────────────────────────────────────────────────────────
    // ─────────────────────────────────────────────────────────────────────────
    // ░░  INFERENCE (Confidence Score logic starts here)  ░░
    // ─────────────────────────────────────────────────────────────────────────
    const cleanText = text.toLowerCase().trim();
    
    // classifier.classify sirf label deta hai, getClassifications poora data deta hai
    const classifications = classifier.getClassifications(cleanText);
    
    // Sabse zyada value wala result nikalne ke liye
    const topResult = classifications.sort((a: any, b: any) => b.value - a.value)[0];
    
    let result: string = topResult.label;
    
    // Confidence score calculation (formatting to 2 decimal places)
    // Agar model trained hai toh score probability ki surat mein aayega
    let accuracy: string = (topResult.value * 100).toFixed(2);

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  HYBRID OVERRIDE RULES  ░░
    //     Rules are 100% accurate because they are hardcoded
    // ─────────────────────────────────────────────────────────────────────────

    // ── Rule 1: Wh- / auxiliary question starters ──
    if (
      /^(who|what|when|where|why|how|which|whom|whose)\b/.test(cleanText) ||
      /^(can we|can you|can someone|could we|could you|should we|shall we)\b/.test(cleanText) ||
      /^(is it|is the|is there|is this|is that|are we|are there|are you|are the)\b/.test(cleanText) ||
      /^(do we|do you|do i|did we|did you|did the|have we|has it|has the|was it|will this|would it)\b/.test(cleanText) ||
      /^(does this|does the|does anyone|does it)\b/.test(cleanText) ||
      /^(any thoughts|any ideas|any suggestions|any update|any progress|any blockers|any concerns|any questions|any volunteers|any help)\b/.test(cleanText) ||
      /^(thoughts on|opinions on|feedback on|help me understand|need clarification|please explain|status update)\b/.test(cleanText)
    ) {
      result = 'question';
      accuracy = '100.00'; // 👈 Kyunki Regex match 100% accurate hota hai
    }

    // ── Rule 2: Explicit question mark ──────────────────────────────────────
    if (cleanText.includes('?')) {
      result = 'question';
    }

    // ── Rule 3: URL / tool domain → reference ───────────────────────────────
    if (
      cleanText.length < 3 ||
      /https?:\/\//.test(cleanText) ||
      /\bwww\.[a-z0-9-]+\.[a-z]{2,}\b/.test(cleanText) ||
      /\b(figma|github|jira|confluence|notion|trello|sentry|datadog|postman|linear|asana|loom|miro|grafana|kibana|pagerduty|newrelic|circleci|vercel|netlify|amplitude|mixpanel|hotjar|sonarqube|codecov|snyk|airtable|zeplin|invision|lucidchart|draw\.io|railway|render)\b/.test(cleanText) ||
      /\b(pr \d+|issue \d+|ticket \d+|commit [a-f0-9]{6,}|v\d+\.\d+[\.\d]*)\b/.test(cleanText) ||
      /\b(ENG|PROJ|BUG|EPIC|BE|FE|INF|OPS|SEC|MOB)-\d+\b/.test(cleanText)
    ) {
      result = 'reference';
    }

    // ── Rule 4: Strong past-tense / outcome signals → decision ───────────────
    if (
      /\b(approved|finalized|decided|confirmed|selected|agreed|rejected|cancelled|canceled|dropped|deprecated|shipped|completed|resolved|locked|concluded|settled|signed off|wrapped up|voted|archived|merged|closed|sunsetting|sunsetted|killed|terminated|accepted|ratified|endorsed|authorized|sanctioned|greenlit|shelved|deprioritized|scrapped|rolled back|reverted|disbanded|adjourned|adopted|committed to|moved forward with)\b/.test(cleanText) &&
      !cleanText.includes('?')
    ) {
      result = 'decision';
    }

    // ── Rule 5: Strong imperative action verbs → action item ────────────────
    //    (must NOT look like a decision or contain a question mark)
    if (
      /\b(fix|build|create|implement|develop|code|add|design|setup|set up|configure|install|deploy|integrate|update|upgrade|refactor|optimize|improve|enhance|clean|rewrite|rebuild|migrate|scale|monitor|track|log|analyze|investigate|research|explore|automate|streamline|secure|protect|write|draft|publish|post|announce|document|schedule|plan|organize|prepare|send|share|review|check|verify|test|validate|audit|assign|delegate|escalate|prioritize|run|execute|generate|arrange|handle|complete|finish|close|report|raise|open|merge|push|commit|sync|backup|restore|patch|rotate|revoke|harden|label|annotate|evaluate|fine-tune|train|retrain|register|book|practice|study|read|submit|upload|download|attach|forward|reply|respond|follow up|ping|remind|inform|buy|purchase|order|manage|call|email|message|notify|present|tag|connect|enable|disable|restart|stop|start|launch|activate|deactivate|remove|delete|drop|rollback|revert|provision|tear down|spin up|spin down|right-size|archive|export|import|load|seed|hydrate|publish|unpublish|release|cut|branch|tag|snapshot|diff|lint|format|transpile|bundle|minify|compress|encrypt|decrypt|hash|sign|verify|stub|mock|intercept|proxy|forward|redirect|reject|permit|whitelist|blacklist|throttle|debounce|queue|dequeue|publish|subscribe|emit|listen|poll|push|pull|clone|fork|cherry-pick)\b/.test(cleanText) &&
      !cleanText.includes('?') &&
      !/\b(approved|finalized|decided|confirmed|selected|agreed|rejected|completed|resolved|done|shipped|concluded|settled|closed|wrapped up|signed off|locked)\b/.test(cleanText)
    ) {
      result = 'action item';
    }

    // ── Rule 6: Soft question phrases (override back to question if needed) ──
    if (
      /\b(what if|how about|how come|any chance|is it possible|could you|mind if|would you|what about|wondering if|curious about|thoughts\?|opinions\?|feedback\?)\b/.test(cleanText) ||
      cleanText.endsWith('?')
    ) {
      result = 'question';
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ░░  LOGGING  ░░
    // ─────────────────────────────────────────────────────────────────────────
    console.log(`[CLASSIFIER] "${text}" → ${result}`);

    return NextResponse.json({ result });

  } catch (error) {
    console.error('Classifier Error:', error);
    return NextResponse.json({ result: 'reference' });
  }
}